use_frameworks!

platform :ios, '8.0'

target 'MyComponentB_Example' do
  pod 'MyComponentB', :path => '../'
  pod 'MyTestRouter'

  target 'MyComponentB_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
